### ISSUE TITLE
Samples no longer compile with C# 7

### ISSUE THREAD

**Issue by SSteve** [shimat/opencvsharp_samples#11]
The sample programs `FaceDetectionDNN.cs`, `HandPose.cs`, `Pose.cs`, and `SiftSurfSample.cs` use the new using declaration (`using var`) available in C# 8. This causes the solution to no longer compile with C# 7. Is this an oversight or by design? (At work we're still using Visual Studio 2017 so C# 8 isn't available to us.)

**Comment by shimat** [comment]
Yes. this is by design. To rewrite C#8 to 7 is easy.

**Comment by SSteve** [comment]
Ok, thanks. Just wanted to make sure.
