### ISSUE TITLE
WindowGUISample errors !!!

### ISSUE THREAD

**Issue by mynameisken** [shimat/opencvsharp_samples#18]
Always get a same error in these functions:

- Windows_Example();
- TrackBar_Example();
- MouseCallBack_Example();

![image](https://user-images.githubusercontent.com/53652743/78005028-92d0ac00-736d-11ea-9296-de1f97dc34a2.png)

![image](https://user-images.githubusercontent.com/53652743/78004983-80ef0900-736d-11ea-8df2-41dfb7637539.png)

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp_samples/blob/b95f9081fd11e79314fa130d29370a43fbe27600/SamplesCS/Samples/WindowGUISample.cs#L10
Please change the file name.
