### ISSUE TITLE
Error BC30649 "Unsupported Type"

### ISSUE THREAD

**Issue by bobdavies2000** [shimat/opencvsharp_samples#23]
With the latest 4/21 version of OpenCVSharp, I am getting this message in VB.Net code on latest Windows 10:

error BC30649: '' is an unsupported type.

You can see this in one of your VB samples - StarDetectorSample - by inserting this line in the Start function:

Dim test = src.At(Of Vec3b)(0, 0)

The variable after the "Of" is unsupported type no matter what type is in there.  A similar change in one of the C# examples does not fail so this appears to only apply to the VB.Net code.

**Comment by shimat** [comment]
Try using Get instead of At. In the latest OpenCvSharp, At returns `ref T` that is probably not supported by VB.NET.
```c#
Vec3b elementVal = src.At<Vec3b>(1, 1);

ref Vec3b elementRef = src.At<Vec3b>(2, 2);
elementRef = new Vec3b(1, 2, 3);

src.At<Vec3b>(0, 0) = new Vec3b(1, 2, 3);
```

**Comment by bobdavies2000** [comment]
I was able to successfully change every "mat.At(" to "mat.Get(" in my code
base.  I am now converted over to the 421 version and everything else looks
like it working so far.  Thanks for the suggestion.

>
