### ISSUE TITLE
PixelAccess example do not work.

### ISSUE THREAD

**Issue by hjy1210** [shimat/opencvsharp_samples#24]
TypeSpecificMat method of PixelAccess class do not work.

It seems

> var mat3 = new Mat\<Vec3b\>(mat);

should be changed to

> var mat3 = MatOfByte3(mat);

**Comment by shimat** [comment]
No, it's an outdated specification.
https://github.com/shimat/opencvsharp/blob/master/src/OpenCvSharp/Modules/core/Mat/MatOfT.cs#L12
