### ISSUE TITLE
Net Core 2.2

### ISSUE THREAD

**Issue by tommy-mtwi** [shimat/opencvsharp_samples#4]
Hi,

Does it support Net Core 2.2? or do you have for Net Core 2.2 version?
I tried to run the sample on Net Core 2.2 but I got Nuget warning that it support 2.0.
the other thing is:
I want to implement this on Linux Environment, but I develop this on Windows, so what Nuget package should I install?

need advise

thanks
Win

**Comment by shimat** [comment]
Thanks. The latest OpenCvSharp supports .NET Core 3.0 (netstandard2.1 and netcoreapp3.0)
https://github.com/shimat/opencvsharp/blob/master/nuget/OpenCvSharp4.nuspec#L30

I published packages for Ubuntu. For other Linux distributions,  For other Linux distributions, please refer to the Dockerfile for Ubuntu.
