### ISSUE TITLE
file "faces.jpg" not found in SampleCore / FaceDetectionDNN Sample

### ISSUE THREAD

**Issue by xsyww** [shimat/opencvsharp_samples#42]
yes, I have downloaded other model files from https://github.com/spmallick/learnopencv/tree/master/FaceDetectionComparison/models and no faces.jpg file was found.

i can't run this sample.

**Comment by shimat** [comment]
https://github.com/shimat/opencvsharp_samples/pull/5
The contributor of the sample code did not provide faces.jpg. You will also need to prepare it yourself.

**Comment by xsyww** [comment]
I got it. this image is the source image that you want to detect face from.  that make sense.
