### ISSUE TITLE
Cleaned up CameraOpenCV sample.

### ISSUE THREAD

**Issue by Noemata** [shimat/opencvsharp_samples#9]
A cleaned up CameraOpenCV sample is located at the fork here:

https://github.com/Noemata/opencvsharp_samples

Everything is working except "Histogram" needs an implementation.  Also, a better approach needs to be resolved for range handling to prevent invalid values.

**Comment by shimat** [comment]
Thanks :+1: I opened a pull request (#10) using your fork.

**Comment by Noemata** [comment]
Do I need to take any action?  I've never had a pull request.

**Comment by shimat** [comment]
I will review your code changes. Then, if necessary, modify the code according to my indication.

**Comment by Noemata** [comment]
Cool.
